# Generated by Django 5.1.5 on 2025-02-23 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FORMS', '0004_dynamicfield_is_active_alter_dynamicfield_field_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicfield',
            name='form',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='FORMS.form'),
        ),
    ]
